steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'apps/game-server/Dockerfile'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/bossroom/game-server:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/bossroom/game-server:latest'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/bossroom/game-server:latest'
